### ISSUE TITLE
hello ，i want to create my dataset, how to generate csv file?

### ISSUE THREAD

**Issue by potoyeee** [PruneTruong/GLU-Net#11]

**Comment by PruneTruong** [comment]
Hi, these transformations were taken from DGC-Net, that generated their transformations before hand. However, they are created by randomly generating homography, TPS and affine transformation. You can have a look at our other repo DenseMatchigng. We have a dataloader which creates the synthetic pairs on the fly at https://github.com/PruneTruong/DenseMatching/blob/main/datasets/synthetic_warp_dataset.py.  Transformations are actually sampled in this folder https://github.com/PruneTruong/DenseMatching/tree/main/utils_data/geometric_transformation_sampling. 
Hope that helps!

**Comment by davidz123** [comment]
@PruneTruong，Hi！
  I am working on your DenseMatching repo. I want to train model with my own data, and accidentally find this issue. After roughly reading the code, I am still wondering how to use geometric_transformation_sampling to generate my own csv-file (cause I did not find the entrance of the functions). Can you show me how to put these codes into use, thanks for your help and  once again thanks for your effort!
