### ISSUE TITLE
RuntimeError: expected type torch.FloatTensor but got torch.LongTensor

### ISSUE THREAD

**Issue by DuNGEOnmassster** [PruneTruong/GLU-Net#19]

**Comment by DuNGEOnmassster** [comment]
Environment:

```
Ubuntu 20.04.5
conda 4.8.2
cupy 11.2.8
cudatoolkit 11.8.0
```

When running

```shell script
python test_GLUNet.py --path_source_image images/yosemite_source.png --path_target_image images/yosemite_target.png --write_dir evaluation/
```

It comes out

<img width="952" alt="image" src="https://user-images.githubusercontent.com/95074892/231088230-2d4f2d21-7e17-45ec-8b2a-c00e3c85e304.png">

**Comment by PruneTruong** [comment]
Hi, 

Seems to me this has something to do with your torch version. Which one are you using? 
I just checked it is running fine for me with torch version 1.7.1. I haven't particularly updated for the newest versions, so there might be some deprecation or differences.

**Comment by DuNGEOnmassster** [comment]
> Hi,
> 
> Seems to me this has something to do with your torch version. Which one are you using? I just checked it is running fine for me with torch version 1.7.1. I haven't particularly updated for the newest versions, so there might be some deprecation or differences.

Thanks. It works!
