### ISSUE TITLE
Missing description of ETH3D testing data

### ISSUE THREAD

**Issue by zehongs** [PruneTruong/GLU-Net#2]
Hi Prune, thanks for the very nice work!

I think you missed the description of ETH3D testing data in README. Will you update it? And I'm wondering the criterion of identifying a potential pair for testing? As you mentioned in the paper: 

> This results in about 500 images pairs in total for each selected interval.

Could you also upload the selected pair ids?

Thanks!

**Comment by PruneTruong** [comment]
Hi, so sorry about that, I was thinking about the best way to share the data and then I forgot about it. I added the evaluation code as well as the pairs and correspondence used. Hope that helps ! Let me know if there is anything else.
