### ISSUE TITLE
Evaluate DGC-Net on hpatches

### ISSUE THREAD

**Issue by drinkingcoder** [PruneTruong/GLU-Net#6]
Hi @PruneTruong ,
Thanks for the great work! I found that DGC-Net can only accept 240x240 image but there are evaluation results of DGC-Net based on the original size of hpatches. Which strategy did you use?

**Comment by PruneTruong** [comment]
Hi, sorry for the delay ! Indeed, DGC-Net only accepts 240x240 images which means that any larger images need to be resized to 240x240 to be given as input to the network, and then the estimated flow upsampled back to original resolution. That's a large disadvantage of these kind of methods that lose a lot of accuracy when applied to high resolution images.

Hope that helps !
