### ISSUE TITLE
Current ADE-20K version is not compatible with training

### ISSUE THREAD

**Issue by ducha-aiki** [PruneTruong/GLU-Net#8]
Hi,

I don't know what can be done wrt this, but you probably should know. 
I have requested access to ADE20K and they provided me with a link. However, after unzipping, directory named `ADE20K_2021_17_01`, not `ADE20K_2016_07_26`, expected by GLU-Net training appears. 
OK, I made a softlink. Then it turns out, that the structure of the dataset has completely changed. 
For example, GLU-Net expects following file:

`ADE20K_2016_07_26/images/training/l/living_room/ADE_train_00000699.jpg`

However, in the current ADE, directory `training` contains no `l`, instead the following dirs:
`cultural  home_or_hotel  industrial  nature_landscape  shopping_and_dining  sports_and_leisure  transportation  unclassified  urban  work_place`.

I believe that `homo_aff_tps_test_DPED_CityScape_ADE.csv` may need regeneration for the current version of the dataset. Moreover, ADE20K website does not allow to download some kind of older version download.

**Comment by PruneTruong** [comment]
Hi, thanks for letting me know ! 
I will see what I can do for generating new csv files with the new version of ADE dataset. In the meantime, I will include a csv file with only CityScapes and DPED images, hopefully training without ADE doesn't impact the network performance too much.
